// Unlock conditions and easter-egg content are base64-encoded so they don't spoil the fun of collecting.
// This is text and numbers only: no program logic, network or file access.
// Want to peek? Call decodeSpoilers(), or paste the string into any base64 decoder.
// Generated by scripts/encode-spoilers.ts. Do not edit by hand.
import { lang, overlay, type Lang } from './i18n'
import type { Spoilers } from './spoiler-types'

export const SPOILERS =
  "eyJjcmFja1RvYXN0Ijoi8J+SpSDllarvvIHom4vooqsgYHtrd31gIOWah+egtOS6huKApuKApuiuiuaIkHtuYW1lfSB7aWNv" +
  "bn0iLCJkYXRlTW9kZSI6eyJiYW5kIjp7ImJhciI6IuS6uumhnuWFpeWRsyIsImZhY2UiOiIowqzigL/CrCkiLCJoaW50cyI6" +
  "WyLkvaDogZ7otbfkvobpgoTlvojnlJ/igKYiLCLkvaDnnIvotbfkvobmnInpu57pubnigKYiLCLkvaDplovlp4vmnInmu7fl" +
  "kbPkuobigKYiLCLkvaDlv6vooqvmu7fpgI/kuobigKYiXSwiaWNvbiI6IvCfkKMiLCJ0aXRsZSI6IuWwj+mbnuato+WcqOa7" +
  "t+S9oCJ9LCJkYXkiOjEsImRleFRpdGxlIjoi5Lq66aGe5ZyW6ZGRIiwiaHVtYW5TdGVwIjoyLCJsaW5lcyI6eyJkYW5nZXIi" +
  "Olsi5Lq66aGe5Y+I5Zyo546p5Y2x6Zqq55qE5p2x6KW/5LqG77yM5bCP6Zue6KaB6Lef5L2g5aq96KybIl0sIm1ha2V1cCI6" +
  "IuaYqOWkqeaYr+aEmuS6uuevgOWWlCDwn4OPIOS9oOmMr+mBjuS6huWwj+mbnu+8jOS9huaEmuS6uuibi+mChOaYr+e1puS9" +
  "oCIsInJldmVhbCI6IvCfjokg5oSa5Lq656+A5b+r5qiC77yB5bCP6Zue5piO5aSp5pyD57iu5Zue6JuL5q686KOh44CC6YCB" +
  "5L2g5LiA6aGG57SA5b+15ZOBIOKGkiIsInRlc3RGYWlsIjpbIuaykumXnOS/gu+8jOS6uumhnuacrOS+huWwseaYr+mAmeao" +
  "oyIsIuWwj+mbnuW3sue2k+e/kuaFo+S6hiJdLCJ0ZXN0UGFzcyI6WyLpm6PlvpfllpTvvIzntabkvaDkuIDpoYbpo7zmlpki" +
  "XSwidHVybiI6WyLmiJHnmoTkurrpoZ7ku4rlpKnlvojkuZbvvIzlj6rlr6vkuoYgMyDlgIsgYnVnIPCfjawiLCLkurrpoZ7l" +
  "j4jlrozmiJDkuIDku7bkuovkuobvvIzlpb3mo5Lmo5IiLCLmu7fkuobkvaDkuIDmlbTlpKnvvIzpgoTmmK/mspLku4Dpurzl" +
  "kbPpgZMiXX0sIm1vbnRoIjo0LCJwcml6ZSI6Ing5IiwicmVwbGllcyI6eyJmbGlwIjoi5bCP6Zue6Kmm5ZyW5oqK5L2g57+7" +
  "6Z2i77yM5aSx5pWX5LqGIiwicmVmaWxsIjoi5bCP6Zue5bmr5L2g5YCS5LqG5LiA5p2v5rC044CC5Lq66aGe6KaB5aSa5Zad" +
  "5rC0IPCfkqcifSwicmV2ZWFsSG91ciI6MTcsInRocm90dGxlTXMiOjYwMDAwMH0sImRleFNsb3RzIjpbImU4IiwiZTYiLCJl" +
  "NCIsImUxIiwiZTciLCJlMyIsImU1IiwiZTIiLCJ4OSJdLCJlZ2dzIjp7ImUxIjp7Imljb24iOiLwn42zIiwibmFtZSI6IuiN" +
  "t+WMheibiyJ9LCJlMiI6eyJpY29uIjoi4pyoIiwibmFtZSI6IumHkeibiyJ9LCJlMyI6eyJpY29uIjoi8J+WpCIsIm5hbWUi" +
  "OiLnmq7om4sifSwiZTQiOnsiaWNvbiI6IvCfp4IiLCJuYW1lIjoi6bm56JuLIn0sImU1Ijp7Imljb24iOiLwn5SpIiwibmFt" +
  "ZSI6IumQteibiyJ9LCJlNiI6eyJpY29uIjoi8J+NsiIsIm5hbWUiOiLmu7fom4sifSwiZTciOnsiaWNvbiI6IuKZqO+4jyIs" +
  "Im5hbWUiOiLmuqvms4nom4sifSwiZTgiOnsiaWNvbiI6IvCfpZoiLCJuYW1lIjoi6Iy26JGJ6JuLIn0sIng5Ijp7Imljb24i" +
  "OiLwn4OPIiwibmFtZSI6IuaEmuS6uuibiyJ9fSwiaGludHMiOnsiZTMiOiLom4vmrrzlpb3lg4/mnInpu57nmbzntqDigKYi" +
  "LCJlNCI6Iuibi+auvOWGkuWHuuS6hum5veiKseKApiIsImU1Ijoi6YCZ6aGG6JuL6LaK5L6G6LaK56Gs5LqG4oCmIiwiZTYi" +
  "OiLogZ7otbfkvobmnInmv4Pmv4PnmoTmu7flkbPigKYiLCJlNyI6IuaRuOi1t+S+hua6q+a6q+i7n+i7n+eahOKApiIsImU4" +
  "Ijoi6Iy26aaZ6LaK5L6G6LaK5r+D5LqG4oCmIn0sImkxOG4iOnsiZW4iOnsiY3JhY2tUb2FzdCI6IvCfkqUgQ3JhY2shIGB7" +
  "a3d9YCBzdGFydGxlZCB0aGUgZWdn4oCmIGl0IHR1cm5lZCBpbnRvOiB7bmFtZX0ge2ljb259IiwiZGF0ZU1vZGUiOnsiYmFu" +
  "ZCI6eyJiYXIiOiJIdW1hbiBmbGF2b3IiLCJoaW50cyI6WyJZb3Ugc3RpbGwgc21lbGwgcmF34oCmIiwiWW91IHRhc3RlIGEg" +
  "Yml0IHNhbHR54oCmIiwiWW91J3JlIHBpY2tpbmcgdXAgZmxhdm9y4oCmIiwiWW91J3JlIGFsbW9zdCBmdWxseSBtYXJpbmF0" +
  "ZWTigKYiXSwidGl0bGUiOiJUaGUgY2hpY2sgaXMgbWFyaW5hdGluZyB5b3UifSwiZGV4VGl0bGUiOiJIdW1hbiBEZXgiLCJs" +
  "aW5lcyI6eyJkYW5nZXIiOlsiVGhlIGh1bWFuIGlzIHBsYXlpbmcgd2l0aCBkYW5nZXJvdXMgc3R1ZmYgYWdhaW4uIFRoZSBj" +
  "aGljayBpcyB0ZWxsaW5nIHlvdXIgbW9tIl0sIm1ha2V1cCI6Illlc3RlcmRheSB3YXMgQXByaWwgRm9vbHMnIERheSDwn4OP" +
  "IFlvdSBtaXNzZWQgdGhlIGNoaWNrLCBidXQgeW91IHN0aWxsIGdldCB0aGUgRm9vbCdzIEVnZyIsInJldmVhbCI6IvCfjokg" +
  "SGFwcHkgQXByaWwgRm9vbHMnIERheSEgVGhlIGNoaWNrIGNyYXdscyBiYWNrIGludG8gaXRzIHNoZWxsIHRvbW9ycm93LiBI" +
  "ZXJlJ3MgYSBzb3V2ZW5pciDihpIiLCJ0ZXN0RmFpbCI6WyJJdCdzIG9rYXksIGh1bWFucyBhcmUganVzdCBsaWtlIHRoYXQi" +
  "LCJUaGUgY2hpY2sgaXMgdXNlZCB0byBpdCBieSBub3ciXSwidGVzdFBhc3MiOlsiV293LCB0aGF0J3MgcmFyZS4gSGF2ZSBz" +
  "b21lIGNoaWNrIGZlZWQiXSwidHVybiI6WyJNeSBodW1hbiB3YXMgZ29vZCB0b2RheSwgb25seSAzIGJ1Z3Mg8J+NrCIsIk15" +
  "IGh1bWFuIGZpbmlzaGVkIGFub3RoZXIgdGhpbmcuIEdvb2Qgam9iISIsIk1hcmluYXRlZCB5b3UgYWxsIGRheSBhbmQgeW91" +
  "IHN0aWxsIHRhc3RlIGxpa2Ugbm90aGluZyJdfSwicmVwbGllcyI6eyJmbGlwIjoiVGhlIGNoaWNrIHRyaWVkIHRvIGZsaXAg" +
  "eW91IG92ZXIuIEl0IGZhaWxlZCIsInJlZmlsbCI6IlRoZSBjaGljayBwb3VyZWQgeW91IGEgZ2xhc3Mgb2Ygd2F0ZXIuIEh1" +
  "bWFucyBuZWVkIHRvIHN0YXkgaHlkcmF0ZWQg8J+SpyJ9fSwiZWdncyI6eyJlMSI6eyJuYW1lIjoiRnJpZWQgRWdnIn0sImUy" +
  "Ijp7Im5hbWUiOiJHb2xkZW4gRWdnIn0sImUzIjp7Im5hbWUiOiJDZW50dXJ5IEVnZyJ9LCJlNCI6eyJuYW1lIjoiU2FsdGVk" +
  "IEVnZyJ9LCJlNSI6eyJuYW1lIjoiSXJvbiBFZ2cifSwiZTYiOnsibmFtZSI6IlNveS1CcmFpc2VkIEVnZyJ9LCJlNyI6eyJu" +
  "YW1lIjoiT25zZW4gRWdnIn0sImU4Ijp7Im5hbWUiOiJUZWEgRWdnIn0sIng5Ijp7Im5hbWUiOiJGb29sJ3MgRWdnIn19LCJo" +
  "aW50cyI6eyJlMyI6IlRoZSBzaGVsbCBsb29rcyBhIGxpdHRsZSBncmVlbuKApiIsImU0IjoiU2FsdCBjcnlzdGFscyBvbiB0" +
  "aGUgc2hlbGzigKYiLCJlNSI6IlRoaXMgZWdnIGtlZXBzIGdldHRpbmcgdG91Z2hlcuKApiIsImU2IjoiU21lbGxzIHJpY2hs" +
  "eSBvZiBzb3kgc2F1Y2XigKYiLCJlNyI6IkZlZWxzIHdhcm0gYW5kIHNvZnTigKYiLCJlOCI6IlNtZWxscyBvZiB0ZWHigKYi" +
  "fX19LCJydWxlcyI6W3siZWdnIjoiZTEiLCJ3aGVuIjoiY3JhY2tlZCJ9LHsiZWdnIjoiZTIiLCJwIjowLjAxLCJ3aGVuIjoi" +
  "Y2hhbmNlIn0seyJkYXlzIjozLCJlZ2ciOiJlMyIsIndoZW4iOiJnYXBBdExlYXN0In0seyJlZ2ciOiJlNCIsIm1pblJ1bnMi" +
  "OjUsInJhdGUiOjAuNSwid2hlbiI6ImZhaWxSYXRlQWJvdmUifSx7ImRheXMiOjIxLCJlZ2ciOiJlNSIsIndoZW4iOiJhZ2VB" +
  "dExlYXN0In0seyJlZ2ciOiJlNiIsIm1pbnV0ZXMiOjEyMCwid2hlbiI6ImF2Z1Nlc3Npb25BYm92ZSJ9LHsiZWdnIjoiZTci" +
  "LCJtaW51dGVzIjoyMCwid2hlbiI6ImF2Z1Nlc3Npb25CZWxvdyJ9LHsiZWdnIjoiZTgiLCJ3aGVuIjoiYWx3YXlzIn1dLCJz" +
  "cHJpdGVzIjp7fSwic3ByaXRlc0hkIjp7fX0="

let raw: Spoilers | null = null
const cache: Partial<Record<Lang, Spoilers>> = {}

// The spoilers in one language (the current UI language by default), each language cached separately
export function decodeSpoilers(l: Lang = lang()): Spoilers {
  const hit = cache[l]
  if (hit) return hit
  if (raw === null) {
    const bytes = Uint8Array.from(atob(SPOILERS), c => c.charCodeAt(0))
    raw = JSON.parse(new TextDecoder().decode(bytes)) as Spoilers
  }
  const { i18n, ...base } = raw
  return (cache[l] = overlay(base, i18n?.[l]))
}
