// Encode the local spoilers.source.json (+ pixel art) into hooks/spoilers.ts.
//
// Usage: npm run encode               generate the file
//        npm run encode -- --check    only check that hooks/spoilers.ts matches the source
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = join(ROOT, 'spoilers.source.json')
const SPRITES = join(ROOT, 'art-build', 'spoiler_sprites.json')
const SPRITES_HD = join(ROOT, 'art-build', 'spoiler_sprites_hd.json')
const OUT =join(ROOT, 'hooks', 'spoilers.ts')
const LINE = 96

const HEADER = `// Unlock conditions and easter-egg content are base64-encoded so they don't spoil the fun of collecting.
// This is text and numbers only: no program logic, network or file access.
// Want to peek? Call decodeSpoilers(), or paste the string into any base64 decoder.
// Generated by scripts/encode-spoilers.ts. Do not edit by hand.
`

const FOOTER = `
let cache: Spoilers | null = null

export function decodeSpoilers(): Spoilers {
  if (cache === null) {
    const bytes = Uint8Array.from(atob(SPOILERS), c => c.charCodeAt(0))
    cache = JSON.parse(new TextDecoder().decode(bytes)) as Spoilers
  }
  return cache
}
`

// Sort object keys so the same source always produces the same string
function sortDeep(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortDeep)
  if (value !== null && typeof value === 'object') {
    return Object.fromEntries(
      Object.keys(value).sort().map(k => [k, sortDeep((value as Record<string, unknown>)[k])]),
    )
  }
  return value
}

function payload(): Record<string, unknown> {
  const data = JSON.parse(readFileSync(SOURCE, 'utf8')) as Record<string, unknown>
  delete data.guard
  if (existsSync(SPRITES)) data.sprites = JSON.parse(readFileSync(SPRITES, 'utf8'))
  data.sprites ??= {}
  data.spritesHd = existsSync(SPRITES_HD) ? JSON.parse(readFileSync(SPRITES_HD, 'utf8')) : {}
  return data
}

function render(data: Record<string, unknown>): string {
  const b64 = Buffer.from(JSON.stringify(sortDeep(data)), 'utf8').toString('base64')
  const chunks: string[] = []
  for (let i = 0; i < b64.length; i += LINE) chunks.push(`"${b64.slice(i, i + LINE)}"`)
  return HEADER + "import type { Spoilers } from './spoiler-types'\n\n" + `export const SPOILERS =\n  ${chunks.join(' +\n  ')}\n` + FOOTER
}

function main(argv: string[]): number {
  const rendered = render(payload())
  if (argv.includes('--check')) {
    const same = existsSync(OUT) && readFileSync(OUT, 'utf8') === rendered
    console.log(same ? '✓ spoilers.ts matches the source' : '✗ spoilers.ts is stale: run npm run encode again')
    return same ? 0 : 1
  }
  writeFileSync(OUT, rendered, 'utf8')
  console.log(`Wrote hooks/spoilers.ts (${rendered.length} chars)`)
  return 0
}

process.exit(main(process.argv.slice(2)))
